apiVersion: skyline.local/v1
kind: CTFChallenge
metadata:
    name: juste-une-photo
    namespace: ctfd
spec:
    name: Juste_Une_Photo
    description: |
        Rien n’a été supprimé. Rien n’a été ajouté.Chaque ligne a été réorganisée selon une règle déterministe. Trouvez le motif, et vous y verrez clair à nouveau.
        #1337
    category: Forensic
    type: standard
    points: 250
    upload_files: true
    creator: Processus Thief
    flag: ENC[AES256_GCM,data:vZbBCqq+aoYIUzgIyaa8pwzysQ==,iv:aXhXLehe2uqFPQD+TvpCS2FR4pJgc/DVkLI/Jvp+BRs=,tag:UAtL2uVpF+J8B+ptcUPH5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-03-28T20:40:43Z"
    mac: ENC[AES256_GCM,data:Lou96ivnpb9d9zqKIkzQEVCIBlB6BcVqFkSrlBKhBAQFxAcxUBS4PfWGz4bBb3VHJGGvrSjGfC+0VZSqjvhaOXQe9ubJqWTh9e7Vx44Ta3eeugDsZAKtqdjAj2i3BYEFoCc0WgxyITgoAbZmcucVymyC2/TWOzLcwVU6m1I6W2M=,iv:DaZvsui86sgYUlYI6OK8n3OuY+OPSsbIZT9KzMR2R8M=,tag:oNUL0ryraI04CojiwEDkTg==,type:str]
    pgp:
        - created_at: "2026-03-28T20:40:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4Wg+3KzyZPEARAAkKYuFJd8L00oDzMjZra4nYDSk5is452qrUI/kiO0zSJ0
            cgRVNc4UhcZ8ZVRO7Ncmb9VVt/ICOqYY1pPfpjBySPgPSQ8H0PV1SVKMt/ljLWIQ
            tZHaCnLbQ9CsI42ugesYI/VnDtxeIF4vAem6hpMxe0Fv7XWCiM7ZF8A3D85/NuC9
            AVX9UsPyOj3ADC478euqGDwzYMUUy75AzniM2JHOEgTB6SK5ofEzxw4eEJsHtCrt
            vEyM/7LjKZLPuHC5FHUFV5RHgL6Q3QI2exYBAFk2OIf7dRl9fumtDQduNNnCbfQR
            hLJCe98K1MW1MeAc30p0BsyK36t2Cy0GOxxhDP4uVcYDJmDy8ls+SXv395o1VoOl
            Gv4ceyAEdfbJS/iUhvTOjEcUAnZEtb24QqOKTmGvAlblBa7XVBllMGqu9nqHiNlY
            p7rjrpF5rOHYxEtr7VNlwdo3F272MaNVASPzeaGSTS8CGvf5Vhc9f2th27J2tD9g
            HtdZcjrHD8Oj1aG/RcEHfQcwQfAPXQnaBnYfyKdMIWP35v2l+TpDflGGS9h91QwS
            t3wZno1h6JVwmVCBRl/tjz2r8B2luds4safp8nlM021qIBpNUSaSV1miFRxtgeoM
            5sgRVELa3/m9QkJjW6Wou5aEFs0VN4NuLtkM8mlV9zRIQW5srwLbMZ28u3jP4c3S
            XgHdjaCJPiehh/rmznSEzEIFTa2aX3AgQgmdRmyqzZp3GAC6Z90j6FQOH1POmFAJ
            HBzUqxyyd0H+M8QDeYqG9WBb9vNbjkip+M0I7Mp1wlBr4s4vy4u0AtouX98oDD8=
            =ACGC
            -----END PGP MESSAGE-----
          fp: 2F678007F08254265530095FB5B68F8BCE0CB069
    encrypted_regex: ^(data|stringData|flag|password|secret)$
    version: 3.8.1
